# Generated by Django 4.2.7 on 2024-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_timestamp_alter_job_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
