# Generated by Django 4.2.7 on 2024-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_name_city_cname_rename_name_state_sname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
