# Generated by Django 4.2.7 on 2024-06-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_state_city_alter_company_city_alter_company_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
