# Generated by Django 4.2.7 on 2024-06-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='desc',
            field=models.TextField(default='Default description'),
        ),
    ]
