# Generated by Django 4.2.7 on 2024-06-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cert_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='cert_upload',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
