# Generated by Django 4.2.7 on 2024-06-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_cert_type_resume_cert_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='welding_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cert_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
