# Generated by Django 4.2.7 on 2024-06-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_current_company_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
