# Generated by Django 4.2.7 on 2024-06-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
