# Generated by Django 4.2.7 on 2024-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_resume_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
