# Generated by Django 4.2.7 on 2024-06-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_state_city_alter_company_city_alter_company_state'),
        ('resume', '0008_resume_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.city'),
        ),
    ]
